// Generated by `npm run db:types` — do not edit by hand.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  graphql_public: {
    Tables: {
      [_ in never]: never;
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      graphql: {
        Args: {
          extensions?: Json;
          operationName?: string;
          query?: string;
          variables?: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      plan_sessions: {
        Row: {
          created_at: string;
          day_index: number;
          description: string | null;
          id: string;
          plan_id: string;
          planned_duration_min: number;
          scheduled_date: string;
          session_type: Database["public"]["Enums"]["session_type"];
          status: Database["public"]["Enums"]["session_status"];
          structure: Json;
          title: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          day_index: number;
          description?: string | null;
          id?: string;
          plan_id: string;
          planned_duration_min: number;
          scheduled_date: string;
          session_type: Database["public"]["Enums"]["session_type"];
          status?: Database["public"]["Enums"]["session_status"];
          structure: Json;
          title: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          day_index?: number;
          description?: string | null;
          id?: string;
          plan_id?: string;
          planned_duration_min?: number;
          scheduled_date?: string;
          session_type?: Database["public"]["Enums"]["session_type"];
          status?: Database["public"]["Enums"]["session_status"];
          structure?: Json;
          title?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "plan_sessions_plan_id_fkey";
            columns: ["plan_id"];
            isOneToOne: false;
            referencedRelation: "plans";
            referencedColumns: ["id"];
          },
        ];
      };
      plans: {
        Row: {
          created_at: string;
          end_date: string;
          equipment_at_generation: Database["public"]["Enums"]["equipment_type"];
          fitness_level_at_generation: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_at_generation: number | null;
          generation_metadata: Json | null;
          goal_at_generation: Database["public"]["Enums"]["training_goal"];
          id: string;
          max_hr_at_generation: number | null;
          start_date: string;
          status: Database["public"]["Enums"]["plan_status"];
          updated_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          end_date: string;
          equipment_at_generation: Database["public"]["Enums"]["equipment_type"];
          fitness_level_at_generation?: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_at_generation?: number | null;
          generation_metadata?: Json | null;
          goal_at_generation: Database["public"]["Enums"]["training_goal"];
          id?: string;
          max_hr_at_generation?: number | null;
          start_date: string;
          status?: Database["public"]["Enums"]["plan_status"];
          updated_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          end_date?: string;
          equipment_at_generation?: Database["public"]["Enums"]["equipment_type"];
          fitness_level_at_generation?: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_at_generation?: number | null;
          generation_metadata?: Json | null;
          goal_at_generation?: Database["public"]["Enums"]["training_goal"];
          id?: string;
          max_hr_at_generation?: number | null;
          start_date?: string;
          status?: Database["public"]["Enums"]["plan_status"];
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          age: number;
          available_days: string[];
          created_at: string;
          equipment_type: Database["public"]["Enums"]["equipment_type"];
          fitness_level: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_source: Database["public"]["Enums"]["ftp_source"] | null;
          ftp_watts: number | null;
          goal: Database["public"]["Enums"]["training_goal"];
          max_hr: number | null;
          max_weekend_minutes: number;
          max_workday_minutes: number;
          updated_at: string;
          user_id: string;
          weight_kg: number;
        };
        Insert: {
          age: number;
          available_days: string[];
          created_at?: string;
          equipment_type: Database["public"]["Enums"]["equipment_type"];
          fitness_level?: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_source?: Database["public"]["Enums"]["ftp_source"] | null;
          ftp_watts?: number | null;
          goal: Database["public"]["Enums"]["training_goal"];
          max_hr?: number | null;
          max_weekend_minutes: number;
          max_workday_minutes: number;
          updated_at?: string;
          user_id: string;
          weight_kg: number;
        };
        Update: {
          age?: number;
          available_days?: string[];
          created_at?: string;
          equipment_type?: Database["public"]["Enums"]["equipment_type"];
          fitness_level?: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_source?: Database["public"]["Enums"]["ftp_source"] | null;
          ftp_watts?: number | null;
          goal?: Database["public"]["Enums"]["training_goal"];
          max_hr?: number | null;
          max_weekend_minutes?: number;
          max_workday_minutes?: number;
          updated_at?: string;
          user_id?: string;
          weight_kg?: number;
        };
        Relationships: [];
      };
      session_logs: {
        Row: {
          actual_duration_min: number;
          km_ridden: number;
          logged_at: string;
          plan_session_id: string;
          rating: number;
        };
        Insert: {
          actual_duration_min: number;
          km_ridden: number;
          logged_at?: string;
          plan_session_id: string;
          rating: number;
        };
        Update: {
          actual_duration_min?: number;
          km_ridden?: number;
          logged_at?: string;
          plan_session_id?: string;
          rating?: number;
        };
        Relationships: [
          {
            foreignKeyName: "session_logs_plan_session_id_fkey";
            columns: ["plan_session_id"];
            isOneToOne: true;
            referencedRelation: "plan_sessions";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      set_session_status: {
        Args: {
          p_actual_duration_min?: number;
          p_km_ridden?: number;
          p_rating?: number;
          p_session_id: string;
          p_status: Database["public"]["Enums"]["session_status"];
        };
        Returns: undefined;
      };
      supersede_and_activate_plan: {
        Args: { p_new_plan_id: string };
        Returns: {
          created_at: string;
          end_date: string;
          equipment_at_generation: Database["public"]["Enums"]["equipment_type"];
          fitness_level_at_generation: Database["public"]["Enums"]["fitness_level"] | null;
          ftp_at_generation: number | null;
          generation_metadata: Json | null;
          goal_at_generation: Database["public"]["Enums"]["training_goal"];
          id: string;
          max_hr_at_generation: number | null;
          start_date: string;
          status: Database["public"]["Enums"]["plan_status"];
          updated_at: string;
          user_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "plans";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
    };
    Enums: {
      equipment_type: "power_meter" | "hrm" | "none";
      fitness_level: "beginner" | "intermediate" | "advanced";
      ftp_source: "measured" | "estimated";
      plan_status: "active" | "expired" | "superseded" | "pending";
      session_status: "pending" | "done" | "skipped";
      session_type: "endurance" | "intervals" | "recovery";
      training_goal: "fitness_health" | "endurance" | "speed_racing";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] & DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      equipment_type: ["power_meter", "hrm", "none"],
      fitness_level: ["beginner", "intermediate", "advanced"],
      ftp_source: ["measured", "estimated"],
      plan_status: ["active", "expired", "superseded", "pending"],
      session_status: ["pending", "done", "skipped"],
      session_type: ["endurance", "intervals", "recovery"],
      training_goal: ["fitness_health", "endurance", "speed_racing"],
    },
  },
} as const;
